module.exports = {
  LOG_TYPE_OK: 'OK',
  LOG_TYPE_DELETE: 'DELETED',
  LOG_TYPE_CREATE: 'CREATED',
  LOG_TYPE_UPDATE: 'UPDATED',
  TYPE_MILESTONE: 'milestone',
  TYPE_LABEL: 'label',
  LABELS_PER_PAGE: 100,
  ISSUES_PER_PAGE: 100,
  MILESTONES_PER_PAGE: 100
};
